import { RotateLoader } from "react-spinners";

type Props = {
  loading: boolean;
};

const Instructions = ({ loading }: Props) => {
  return (
    <>
      <div className="absolute h-12 w-12 top-5 right-5 bg-secondary rounded-full" />
      <div className="absolute h-12 w-12 bottom-5 left-5 bg-secondary rounded-full" />
      <div className="w-full border border-gray-200 py-6 px-10 rounded-3xl bg-white flex flex-col gap-8">
        {loading ? (
          <div className="flex flex-col justify-center items-center flex-1 gap-10">
            <RotateLoader color="#5500ff" />
            <p className="font-quicksand-600 text-gray-400">Reading file and classifying...</p>
          </div>
        ) : (
          <>
            <h1 className="text-center font-quicksand-700 text-primary text-xl">Instructions</h1>
            <div className="h-full font-quicksand-400 flex flex-col gap-5 mb-14">
              <p className="">
                You can either drag and drop a file to the designed area or click and browse the file you want to be
                classified.
              </p>
              <p className="">You may also type in on the text box the body of the email you want to classify.</p>
              <p className="">After you finish uploading ou typing in, you can press the classify or reply button.</p>
              <p className="">
                The email will be classified as “Productive” or “Unproductive” depending on its contents.
              </p>
              <p className="">
                A small reply can also be generated by pressing the reply button, it will try to create a custom
                response based on the contents and the sender.
              </p>
            </div>
          </>
        )}
      </div>
    </>
  );
};

export default Instructions;
